name: Laser_commissioning_24
channels:
  - conda-forge
dependencies:
  - cuda-version==11.8
  - python==3.11
  - numpy==1.25
  - cupy==12.0
  - xarray
  - pycuda==2022.2
  - ipywidgets
  - ipympl
  - scipy
  - scikit-image
  - tqdm
  - scikit-beam
  - black-jupyter
  - scikit-learn
  - numba
  - dask
  - dipy
  - isort
  - jupyterlab-git
  - nexusformat
  - imagemagick
  - wand
  - astropy
  - ccdproc
  - dxchange
  - pyfai

